"""
similarity.py
-------------
Visual similarity search: embed a query image with the CNN's penultimate
feature layer, then look up the nearest neighbors in a FAISS index built
from a reference dataset.

This module is infrastructure-first and honest about its own availability:
if `faiss` isn't installed, or no index has been built yet (see
`build_index_from_embeddings` and models/README.md), `search()` returns
{"available": False, "message": "..."} rather than fabricating results.

Similarity is a visual-nearness signal only. It is never translated into a
diagnosis or probability, and every response carries that disclaimer.
"""

from __future__ import annotations

import json
import logging
from typing import Any, Dict, List, Optional

import numpy as np

try:
    from . import config
except ImportError:
    import config

logger = logging.getLogger("edge_ai_triage.similarity")

try:
    import faiss  # type: ignore

    _FAISS_AVAILABLE = True
except ImportError:
    faiss = None  # type: ignore
    _FAISS_AVAILABLE = False
    logger.info("faiss is not installed — similarity search will report unavailable.")


class SimilarityIndex:
    """Loads a prebuilt FAISS index + metadata sidecar file, if present."""

    def __init__(self) -> None:
        self._index = None
        self._metadata: List[Dict[str, Any]] = []
        self._loaded = False
        self._load()

    def _load(self) -> None:
        if not _FAISS_AVAILABLE:
            return
        index_path = config.SIMILARITY_INDEX_FILE
        metadata_path = config.SIMILARITY_METADATA_FILE
        if not (index_path.is_file() and metadata_path.is_file()):
            return
        try:
            self._index = faiss.read_index(str(index_path))
            # Similarity indices generated by v0.2.1 use normalized vectors
            # with inner-product search (cosine similarity). Reject older
            # L2 indices rather than silently displaying an incompatible score.
            if getattr(self._index, "metric_type", None) != getattr(faiss, "METRIC_INNER_PRODUCT", 0):
                logger.warning("Similarity index uses an unsupported metric; rebuild it with tools/build_similarity_index.py.")
                self._index = None
                return
            with open(metadata_path, "r", encoding="utf-8") as f:
                self._metadata = json.load(f)
            if len(self._metadata) != self._index.ntotal:
                logger.warning("Similarity index metadata count does not match index size; search disabled.")
                self._index = None
                self._metadata = []
                return
            self._loaded = True
            logger.info("Loaded similarity index with %d entries from %s", len(self._metadata), index_path)
        except Exception as exc:  # pragma: no cover
            logger.warning("Failed to load similarity index (%s); similarity search disabled.", exc)
            self._index = None
            self._metadata = []
            self._loaded = False

    @property
    def available(self) -> bool:
        return _FAISS_AVAILABLE and self._loaded

    def search(self, embedding: List[float], top_k: Optional[int] = None) -> Dict[str, Any]:
        if not self.available:
            reason = (
                "faiss is not installed in this environment."
                if not _FAISS_AVAILABLE
                else "No similarity index has been built yet. See models/README.md."
            )
            return {"available": False, "message": f"Similarity search is not configured yet. {reason}", "matches": []}

        top_k = top_k or config.SIMILARITY_TOP_K
        query = np.array([embedding], dtype="float32")
        norm = np.linalg.norm(query, axis=1, keepdims=True)
        query = query / np.maximum(norm, 1e-12)
        distances, indices = self._index.search(query, top_k)

        matches = []
        for distance, idx in zip(distances[0], indices[0]):
            if idx < 0 or idx >= len(self._metadata):
                continue
            entry = self._metadata[idx]
            # The index builder uses normalized vectors + inner product, so
            # this is cosine similarity. Map [-1, 1] to [0, 1] for display.
            similarity_score = float((float(distance) + 1.0) / 2.0)
            matches.append(
                {
                    "label": entry.get("label"),
                    "similarity_score": round(similarity_score, 4),
                    "thumbnail_base64": entry.get("thumbnail_base64"),
                }
            )

        return {"available": True, "message": "", "matches": matches}


def build_index_from_embeddings(embeddings: np.ndarray, metadata: List[Dict[str, Any]]) -> None:
    """
    Build and persist a flat inner-product FAISS index from precomputed embeddings.

    Intended to be called from an offline script once a reference dataset
    and trained (or at least fine-tuned) embedding model are available — not
    from a request path. `metadata` must be the same length as `embeddings`
    and align 1:1 (label + optional thumbnail per row).
    """
    if not _FAISS_AVAILABLE:
        raise RuntimeError("faiss is not installed; run `pip install faiss-cpu` to build a similarity index.")
    if len(embeddings) != len(metadata):
        raise ValueError("embeddings and metadata must have the same length")

    config.SIMILARITY_INDEX_DIR.mkdir(parents=True, exist_ok=True)
    dimension = embeddings.shape[1]
    matrix = np.ascontiguousarray(embeddings, dtype="float32")
    norms = np.linalg.norm(matrix, axis=1, keepdims=True)
    matrix = matrix / np.maximum(norms, 1e-12)
    index = faiss.IndexFlatIP(dimension)
    index.add(matrix)

    faiss.write_index(index, str(config.SIMILARITY_INDEX_FILE))
    with open(config.SIMILARITY_METADATA_FILE, "w", encoding="utf-8") as f:
        json.dump(metadata, f)

    logger.info("Wrote similarity index with %d entries to %s", len(metadata), config.SIMILARITY_INDEX_FILE)
